const date = new Date();
const name = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const dummyarrr = [
  {
    date: new Date(),
    title: "Best Practices for App Development and Production",
    instructor: "Usama Sarwar",
    certified: "Google Certified Flutter Development at Google",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Best Practices for App Development and Production",
    instructor: "Usama Sarwar",
    certified: "Google Certified Flutter Development at Google",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Best Practices for App Development and Production",
    instructor: "Usama Sarwar",
    certified: "Google Certified Flutter Development at Google",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Best Practices for App Development and Production",
    instructor: "Usama Sarwar",
    certified: "Google Certified Flutter Development at Google",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
  {
    date: new Date(),
    title: "Best Practices for App Development and Production",
    instructor: "Usama Sarwar",
    certified: "Google Certified Flutter Development at Google",
    current: "Upcomming",
    month: name[date.getMonth()],
    year: date.getFullYear(),
    day: date.getDate(),
  },
];
export default dummyarrr;
